### ISSUE TITLE
Dropdown in Navbar malfunctioning

### ISSUE THREAD

**Issue by OrionOth** [OrionOth/unit3#1]
```html
  <ul> <!--Navbar-->
    <li><a href="index.html">Home</a></li>
    <li><a href="resources/cats.html">Meet The Cats</a></li>
    <li><a href="resources/about.html">About us</a></li>
    <!--\/Currently useless :(-->
    <li>
      <div class="dropdown">
        <button class="dropbtn">Dropdown</button>
        <div class="dropdown-content">
          <a href="#">Link 1</a>
          <a href="#">Link 2</a>
          <a href="#">Link 3</a>
        </div>
      </div>
    </li>
  </ul><!--//EndNavbar-->
```
```css
ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #00bbec;
    font-family: sans-serif;
}

li{
    float: left;
}

li a{
    display: block;
    color: white;
    text-align: center;
    padding: 14px 12px;
    text-decoration: none;
}

li a:hover{
    background-color: #8ce6ea;
}
/*Thanks to w3schools for this block of code here. I am currently debugging it;
the code itself is fine, it just isn't currently compatible with the navbar,
the basic design of which is also from w3schools.*/
/*So from here down to the next comment is currently broken; I will be
continuing to work my hardest to fix this bug. I believe it has to do with the
ordering of the elements of the page in index.html, however I couldn't say. I
do desire this dropdown to be located after the navbar, though.*/
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 14px 12px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {
  background-color: #f1f1f1;
}

.dropdown:hover .dropdown-content {
    display: block;
  }

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
/*So, the code from the previous comment to this one is broken right now, but
the problem almost certainly has something to do with the navbar, so I will
continue debugging in earnest.*/
```
