### ISSUE TITLE
Dropdown arrow malfunctioning

### ISSUE THREAD

**Issue by OrionOth** [OrionOth/unit3#2]
The dropdown arrow is malfunctioning; [[ & ]] signify the issue
```html
        <div class="dropdown">
          <button class="dropbtn"><a href="resources/life.html">The Life[[<i class="arrow down">]]</i></a></button>
          <div class="dropdown-content">
            <a href="#">These</a>
            <a href="#">Are</a>
            <a href="#">All</a>
            <a href="#">Fake!</a>
          </div>
        </div>
```
```css
i {
    border: solid white;
    border-width: 0 3px 3px 0;
    display: inline-block;
    padding: 3px;
    color: white;
}

.down {
    transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
}

```
